#R packages
library(shiny)
library(shinythemes)
library(MESS)
library(wmwpow)
library(WMWssp)

#R shiny user interface
ui <- fluidPage(theme = shinytheme("cosmo"),
  #App title and navigaition bar
  navbarPage(
    "Select calculation:",
      #First navigation tab
      tabPanel("Normality and variance calculation",
        #Side panel
        sidebarPanel(
          tags$h3("Data input:"),
          textInput("var1", "Variable 1:", ""),
          textInput("var2", "Variable 2:", ""),
          sliderInput(inputId = "bins",
                      label = "Number of bins:",
                      min = 1,
                      max = 50,
                      value = 25),
          actionButton("example_data", "Example data")
        ),
        #Main pabel    
        mainPanel(
          tags$label(h3('Histogram:')),
          plotOutput('Plot'),
          tags$label(h3('Normality and equal variance results:')),
          tableOutput('tabledata_3')
        )
      ),
      #Second navigation tab
      tabPanel("Hypothesis testing and power calculation",
        #Side panel
        sidebarPanel(
          tags$h3("Data input:"),
          textInput("var3", "Variable 1:", ""),
          textInput("var4", "Variable 2:", ""),
          selectInput("type_of_test", label = "Type of test:", 
            choices = list("Unpaired 2-tailed Student's t-test" = "unpaired_2_tailed_students_t_test", 
                            "Paired 2-tailed Student's t-test" = "paired_2_tailed_students_t_test",
                            "Unpaired 2-tailed Welch's t-test" = "unpaired_2_tailed_welchs_t_test", 
                            "Paired 2-tailed Welch's t-test" = "paired_2_tailed_welchs_t_test",
                            "Unpaired 2-tailed Wilcoxon test" = "unpaired_2_tailed_wilcoxon_test",
                            "Paired 2-tailed Wilcoxon test" = "paired_2_tailed_wilcoxon_test")),
          actionButton("example_data1", "Example data"),
          actionButton("submitbutton", "Submit", class = "btn btn-primary"),
          tags$label(h5("Example data may not be suitable for all statistical tests. New data can be generated by selecting the Example data button"))
        ),
        #Main panel
        mainPanel(
          tags$label(h3('Information:')), 
          htmlOutput('contents'),
          tags$label(h3('Results:')),
          tableOutput('tabledata'),
          tableOutput('tabledata_2')
        )
      )
    )
  )


#R shiny server 
server <- function(input, output, session){
  #Following code generate example data
  #Create and input example data for normality and variance calculations- activates upon selecting the example_data button    
  observeEvent(input$example_data, {
    #Generates normal data for var1
    updateTextInput(session, "var1", value = (paste(signif(rnorm(50, mean=50, sd=10), digits = 3), collapse = ", " )))
    #Generates normal data for var2
    updateTextInput(session, "var2", value = (paste(signif(rnorm(50, mean=50, sd=10), digits = 3), collapse = ", " )))
  })
  #Create and input example data for hypothesis testing and power calculations- activates upon selecting the xample_data1 button   
  observeEvent(input$example_data1, {
    #Generates random data between 1-20 for var3
    updateTextInput(session, "var3", value = (paste((sample(1:20, 25, replace=TRUE)), collapse = ", " )))
    #Generates random data between 1-20 for var4
    updateTextInput(session, "var4", value = (paste((sample(2:25, 25, replace=TRUE)), collapse = ", " )))
  })
  
  #Following code is for the first navigation tab
  #Generate histogram
  output$Plot <- renderPlot({
    #Execute only if data has been input
    if(((input$var1 >0) == TRUE) | ((input$var2 >0) == TRUE)){
      #Removes non numerical characters, omits NAs and combins data for histogram
      var1<- as.numeric(strsplit(gsub("\t| |, |,| ;|;",",", input$var1), "," )[[1]])
      var2<- as.numeric(strsplit(gsub("\t| |, |,| ;|;",",", input$var2), ",")[[1]])
      var1<- na.omit(var1)
      var2<- na.omit(var2)
      x <- c(var1, var2)
      x <- na.omit(x)
     #Execute only if there are more than one unique character    
      if(is.na(var(x)) == FALSE){
        if ((var(x) == 0) == FALSE){
          #Chnage bin size as per user input
          bins <- seq(min(x), max(x), length.out = input$bins + 1)
          #Generate histogram
          hist(x, breaks= bins, xlab = "Data input", ylab= "Density",
              main = "Frequency distribution", col= "lightgray", freq = FALSE)
        }
      }
    }
  })
  #Conduct normality and variance calculations  
  output$tabledata_3<-renderTable({
    #Execute only if data has been input
    if(((input$var1 >0) == TRUE) | ((input$var2 >0) == TRUE)){
      #Removes non numerical characters, omits NAs and combins data for normality calculations
      var1<- as.numeric( strsplit(gsub("\t| |, |,| ;|;",",", input$var1), "," )[[1]])
      var2<- as.numeric(strsplit(gsub("\t| |, |,| ;|;",",", input$var2), ",")[[1]])
      var1<- na.omit(var1)
      var2<- na.omit(var2)
      x <- c(var1, var2)
      x <- na.omit(x)
      #Execute only if there are more than one unique character      
      if(is.na(var(x)) == FALSE){
        if (((var(x) == 0) == FALSE) & 
            ((length(x) >= 3) == TRUE)){
          #Execute only if both var1 and var2 conatin more than or equal to two characters each and five characters overall  
          if(((length(var1) >= 2) == TRUE) &
              ((length(var2) >= 2) == TRUE) &
              ((length(x) >= 5) == TRUE)){
                #Conduct normality and variance calculations and create a dataframe
                normality_result<- signif(shapiro.test(x)[["p.value"]], digits = 3)
                variance_result<-  signif(var.test(var1, var2)[["p.value"]], digits = 3)
                df <- data.frame(
                  Normality =  paste(normality_result, collapse = ", "),
                  Equal_variance = paste(variance_result, collapse = ", "))
                colnames(df)<- c("Normality", "Equal variance")
                df <- df
            }else{
                #Else conduct normality calculation only and create a dataframe
                normality_result<- signif(shapiro.test(x)[["p.value"]], digits = 3)
                df <- data.frame(Normality =  paste(normality_result, collapse = ", "))
                colnames(df)<- c("Normality")
                df <- df
                }
          }
        }
      }
    })
  
  #Following code is for the second navigation tab 
  #Mean and confidence interval calulations
  datasetInput <- reactive({
    #Removes non numerical characters and omits NAs 
    var3<- as.numeric( strsplit(gsub("\t| |, |,| ;|;",",", input$var3), "," )[[1]])
    var4<- as.numeric(strsplit(gsub("\t| |, |,| ;|;",",", input$var4), ",")[[1]])
    var3<- na.omit(var3)
    var4<- na.omit(var4)
    var3_mean<- mean(var3)
    var4_mean<- mean(var4)
    # Calculate confidence interval using selected test
    if ((input$type_of_test == "unpaired_2_tailed_students_t_test")|
        (input$type_of_test == "paired_2_tailed_students_t_test")|
        (input$type_of_test == "unpaired_2_tailed_welchs_t_test")|
        (input$type_of_test == "paired_2_tailed_welchs_t_test")){
          var3_CI<- signif(t.test(var3, conf.level = 0.95)[["conf.int"]], digits = 3)
          var4_CI<- signif(t.test(var4, conf.level = 0.95)[["conf.int"]], digits = 3)
    }
    if ((input$type_of_test == "unpaired_2_tailed_wilcoxon_test")|
        (input$type_of_test == "paired_2_tailed_wilcoxon_test")){
          var3_CI<- signif(wilcox.test(var3, conf.int = TRUE, conf.level = 0.95)[["conf.int"]], digits = 3)
          var4_CI<- signif(wilcox.test(var4, conf.int = TRUE, conf.level = 0.95)[["conf.int"]], digits = 3)
    }
    #Create dataframe  
    df <- data.frame(
      Variable = c("1","2"),
      Mean = c(var3_mean,var4_mean),
      Confidence_intervals =  c(paste(var3_CI, collapse = ", "), paste(var4_CI, collapse = ", "))
      
    )
    colnames(df)<- c("Variable", "Mean", "Confidence intervals")
    df <- df
  })
  #Display results from mean and confidence interval calculations when the submitbutton has been selected
  output$tabledata <- renderTable({
      if (input$submitbutton>0) { 
        isolate(datasetInput()) 
      } 
    })
  #Hypothesis and power calculations
  datasetInput_2 <- reactive({  
    #Removes non numerical characters and omits NAs 
    var3<- as.numeric(strsplit(gsub("\t| |, |,| ;|;",",", input$var3), "," )[[1]])
    var4<- as.numeric(strsplit(gsub("\t| |, |,| ;|;",",", input$var4), ",")[[1]])
    var3<- na.omit(var3)
    var4<- na.omit(var4)
    var3_mean<- mean(var3)
    var4_mean<- mean(var4)
    var3_sd<- sd(var3)
    var4_sd<- sd(var4)
    cohens_d<- signif((abs(var3_mean-var4_mean))/sqrt( ((var3_sd^2)+(var4_sd^2))/2), digits = 3)
    #Data preparation for power calculation
    #Calculate the sample size and sample size ratio so that the lowest sample size is taken, and the ratio is always >=1
    if(length(var3) == length(var4)){
      power_n<- as.numeric(length(var3))
      power_n_ratio<- length(var3)/length(var4)
    }else{
      if(length(var3) > length(var4)){
        power_n<- as.numeric(length(var4))
        power_n_ratio<- length(var3)/length(var4)
      }else{
        if(length(var3) < length(var4)){
          power_n<- as.numeric(length(var3))
          power_n_ratio<- length(var4)/length(var3)
        }
      }
    }
    #Calculate the standard deviation and standard deviation ratio so that the lowest standard deviation is taken, and the ratio is always >=1
    if(var3_sd == var4_sd){
      power_sd<- var3_sd
      power_sd_ratio<- var3_sd/var4_sd
    }else{
      if(var3_sd > var4_sd){
        power_sd<- var4_sd
        power_sd_ratio<- var3_sd/var4_sd
        }else{
          if(var3_sd < var4_sd){
            power_sd<- var3_sd
            power_sd_ratio<- var4_sd/var3_sd
          }
        }
      }
    #Hypothesis testing and power calculations by unpaired 2-tailed Student's t-test
    if (input$type_of_test == "unpaired_2_tailed_students_t_test"){
    test_CI<- signif(t.test(var3, var4, paired = FALSE, var.equal = TRUE, alternative = "two.sided", conf.level = 0.95)[["conf.int"]], digits = 3)
    test_p_value<- signif(t.test(var3, var4, paired = FALSE, var.equal = TRUE, alternative = "two.sided", conf.level = 0.95)[["p.value"]], digits = 3)
    #Studnet's t-test power analysis
    power_result<- power_t_test(n = power_n, delta = (abs((var3_mean-var4_mean))), sd = power_sd, sig.level = 0.05, power = NULL, ratio = power_n_ratio, sd.ratio = power_sd_ratio, 
                                 type = "two.sample", alternative = "two.sided", df.method = "classical")
    power_result<- signif(power_result$power, digits = 3)
    #Studnet's t-test ideal sample size analysis
    #If power is equal to 100%, do not calculate ideal sample size- print "NA"
    if(power_result < 1){
    sample_size_result<- power_t_test(n = NULL, delta = (abs((var3_mean-var4_mean))), sd = power_sd, sig.level = 0.05, power = 0.8, ratio = 1, sd.ratio = power_sd_ratio, 
                                       type = "two.sample", alternative = "two.sided", df.method = "classical")
    sample_size_result<- round(sample_size_result$n, digits = 0)
    sample_size_result<- paste(sample_size_result, sample_size_result, sep = ", ")[[1]]
    }else{
      sample_size_result<- paste("NA")
    }
  }
    #Hypothesis testing and power calculations by paired 2-tailed Student's t-test
    if (input$type_of_test == "paired_2_tailed_students_t_test"){
      test_CI<- signif(t.test(var3, var4, paired = TRUE, var.equal = TRUE, alternative = "two.sided", conf.level = 0.95)[["conf.int"]], digits = 3)
      test_p_value<- signif(t.test(var3, var4, paired = TRUE, var.equal = TRUE, alternative = "two.sided", conf.level = 0.95)[["p.value"]], digits = 3)
      #Studnet's t-test power analysis
      power_result<- power_t_test(n = power_n, delta = (abs((var3_mean-var4_mean))), sd = power_sd, sig.level = 0.05, power = NULL, ratio = power_n_ratio, sd.ratio = power_sd_ratio, 
                                  type = "paired", alternative = "two.sided", df.method = "classical")
      power_result<- signif(power_result$power, digits = 3)
      #Studnet's t-test ideal sample size analysis
      #If power is equal to 100%, do not calculate ideal sample size- print "NA"
      if(power_result < 1){
        sample_size_result<- power_t_test(n = NULL, delta = (abs((var3_mean-var4_mean))), sd = power_sd, sig.level = 0.05, power = 0.8, ratio = 1, sd.ratio = power_sd_ratio, 
                                          type = "paired", alternative = "two.sided", df.method = "classical")
        sample_size_result<- round(sample_size_result$n, digits = 0)
        sample_size_result<- paste(sample_size_result, sample_size_result, sep = ", ")[[1]]
        }else{
        sample_size_result<- paste("NA")
      }
    }
    #Hypothesis testing and power calculations by unpaired 2-tailed Welch's t-test
    if (input$type_of_test == "unpaired_2_tailed_welchs_t_test"){
      test_CI<- signif(t.test(var3, var4, paired = FALSE, var.equal = FALSE, alternative = "two.sided", conf.level = 0.95)[["conf.int"]], digits = 3)
      test_p_value<- signif(t.test(var3, var4, paired = FALSE, var.equal = FALSE, alternative = "two.sided", conf.level = 0.95)[["p.value"]], digits = 3)
      #welch's t-test power analysis
      power_result<- power_t_test(n = power_n, delta = (abs((var3_mean-var4_mean))), sd = power_sd, sig.level = 0.05, power = NULL, ratio = power_n_ratio, sd.ratio = power_sd_ratio, 
                                  type = "two.sample", alternative = "two.sided", df.method = "welch")
      power_result<- signif(power_result$power, digits = 3)
      #welch's t-test ideal sample size analysis
      #If power is equal to 100%, do not calculate ideal sample size- print "NA"
      if(power_result < 1){
        sample_size_result<- power_t_test(n = NULL, delta = (abs((var3_mean-var4_mean))), sd = power_sd, sig.level = 0.05, power = 0.8, ratio = 1, sd.ratio = power_sd_ratio, 
                                          type = "two.sample", alternative = "two.sided", df.method = "welch")
        sample_size_result<- round(sample_size_result$n, digits = 0)
        sample_size_result<- paste(sample_size_result, sample_size_result, sep = ", ")[[1]]
        }else{
        sample_size_result<- paste("NA")
      }
    }
    #Hypothesis testing and power calculations by paired 2-tailed Welch's t-test
    if (input$type_of_test == "paired_2_tailed_welchs_t_test"){
      test_CI<- signif(t.test(var3, var4, paired = TRUE, var.equal = FALSE, alternative = "two.sided", conf.level = 0.95)[["conf.int"]], digits = 3)
      test_p_value<- signif(t.test(var3, var4, paired = TRUE, var.equal = FALSE, alternative = "two.sided", conf.level = 0.95)[["p.value"]], digits = 3)
      #welch's t-test power analysis
      power_result<- power_t_test(n = power_n, delta = (abs((var3_mean-var4_mean))), sd = power_sd, sig.level = 0.05, power = NULL, ratio = power_n_ratio, sd.ratio = power_sd_ratio, 
                                  type = "paired", alternative = "two.sided", df.method = "welch")
      power_result<- signif(power_result$power, digits = 3)
      #welch's t-test ideal sample size analysis
      #If power is equal to 100%, do not calculate ideal sample size- print "NA"
      if(power_result < 1){
        sample_size_result<- power_t_test(n = NULL, delta = (abs((var3_mean-var4_mean))), sd = power_sd, sig.level = 0.05, power = 0.8, ratio = 1, sd.ratio = power_sd_ratio, 
                                          type = "paired", alternative = "two.sided", df.method = "welch")
        sample_size_result<- round(sample_size_result$n, digits = 0)
        sample_size_result<- paste(sample_size_result, sample_size_result, sep = ", ")[[1]]
        }else{
        sample_size_result<- paste("NA")
      }
    }
    #Hypothesis testing and power calculations by unpaired wilcoxon mann whitney U test 
    if (input$type_of_test == "unpaired_2_tailed_wilcoxon_test"){
      test_CI<- signif(wilcox.test(var3, var4, paired = FALSE, alternative = "two.sided", conf.int = TRUE, conf.level = 0.95)[["conf.int"]], digits = 3)
      test_p_value<- signif(wilcox.test(var3, var4, paired = FALSE, alternative = "two.sided", conf.int = TRUE, conf.level = 0.95)[["p.value"]], digits = 3)
      #Wilcoxon mann whitney u rank sum test power analysis
      invisible(capture.output(
      power_result<- shiehpow(n=(as.numeric(length(var3))), m=(as.numeric(length(var4))), p=1-test_p_value, alpha = 0.05, dist = "norm", sides = "two.sided")
      ))
      power_result<- signif(power_result$power, digits = 3)
      #Wilcoxon mann whitney u rank sum test ideal sample size analysis
      sample_size_result<- WMWssp(var3, var4, alpha = 0.05, power = 0.8, t = 0.5)
      sample_size_result<- paste(c(((sample_size_result$N)/2),((sample_size_result$N)/2)), collapse = ", ")[[1]]
    }
    #Hypothesis testing and power calculations by paired wilcoxon mann whitney U test 
    if (input$type_of_test == "paired_2_tailed_wilcoxon_test"){
      test_CI<- signif(wilcox.test(var3, var4, paired = TRUE, alternative = "two.sided", conf.int = TRUE, conf.level = 0.95)[["conf.int"]], digits = 3)
      test_p_value<- signif(wilcox.test(var3, var4, paired = TRUE, alternative = "two.sided", conf.int = TRUE, conf.level = 0.95)[["p.value"]], digits = 3)
      #Wilcoxon mann whitney u rank sum test power analysis
      invisible(capture.output(
      power_result<- shiehpow(n=(as.numeric(length(var3))), m=(as.numeric(length(var4))), p=1-test_p_value, alpha = 0.05, dist = "norm", sides = "two.sided")
      ))
      power_result<- signif(power_result$power, digits = 3)
      #Wilcoxon mann whitney u rank sum test ideal sample size analysis
      sample_size_result<- WMWssp(var3, var4, alpha = 0.05, power = 0.8, t = 0.5)
      sample_size_result<- paste(c(((sample_size_result$N)/2),((sample_size_result$N)/2)), collapse = ", ")[[1]]
    }
    #Create data fram from calculated statistics
    df <- data.frame(
      Confidence_intervals =  paste(test_CI, collapse = ", "),
      Cohens_d = paste(cohens_d, collapse = ", "),
      P_value = paste(test_p_value, collapse = ", "),
      Power = paste(power_result, collapse = ", "),
      Sample_size = paste(sample_size_result, collapse = ", ")
    )
    colnames(df) <- c("Confidence intervals", "Cohen's d", "P value", "Power", "Sample size")
    df <- df
  })
  #Generate hypothesis testing and power calculation data frame if submitbutton has been selected
  output$tabledata_2 <- renderTable({
    if (input$submitbutton>0){ 
      isolate(datasetInput_2()) 
    } 
  })
  #Information regarding selected statistical test
  output$contents <- renderPrint({
      return(
        if(input$type_of_test == "unpaired_2_tailed_students_t_test"){
          return("Unpaired two-tailed Student's t-test will be conducted using R: t.test and power_t_test. Code adapted from Sultan et al., 2021 (https://doi.org/10.3389/fcell.2021.726281)")
        } else if (input$type_of_test == "paired_2_tailed_students_t_test"){
          return("Paired two-tailed Student's t-test will be conducted using R: t.test and power_t_test. Code adapted from Sultan et al., 2021 (https://doi.org/10.3389/fcell.2021.726281)")
        }else if (input$type_of_test == "unpaired_2_tailed_welchs_t_test"){
          return("Unpaired two-tailed Welch's t-test will be conducted using R: t.test and power_t_test. Code adapted from Sultan et al., 2021 (https://doi.org/10.3389/fcell.2021.726281)")
        }else if (input$type_of_test == "paired_2_tailed_welchs_t_test"){
          return("Paired two-tailed Welch's t-test will be conducted using R: t.test and power_t_test. Code adapted from Sultan et al., 2021 (https://doi.org/10.3389/fcell.2021.726281)")
        }else if (input$type_of_test == "unpaired_2_tailed_wilcoxon_test"){
          return("Unpaired two-tailed WMW test will be conducted using R: wilcox.test, shiehpow, and WMWssp. Code adapted from Sultan et al., 2021 (https://doi.org/10.3389/fcell.2021.726281)")
        }else if (input$type_of_test == "paired_2_tailed_wilcoxon_test"){
          return("Paired two-tailed WMW test will be conducted using R: R: wilcox.test, shiehpow, and WMWssp. Code adapted from Sultan et al., 2021 (https://doi.org/10.3389/fcell.2021.726281)")
        }
      ) 
    })
}
  
#Coupling of shiny UI and Server
shinyApp(ui = ui, server = server)
